# Generated by Django 6.0

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_uuid_primary_keys"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="phone",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
