# Generated by Django 6.0.3

from django.db import migrations, models


def ensure_single_org_settings(apps, schema_editor):
    OrganizationSettings = apps.get_model('api', 'OrganizationSettings')
    if not OrganizationSettings.objects.exists():
        OrganizationSettings.objects.create()


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_userprofile_display_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsettings',
            name='smtp_enabled',
            field=models.BooleanField(
                default=False,
                help_text='When set, use these SMTP settings instead of the server .env e-mail config.',
            ),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='smtp_from_email',
            field=models.EmailField(
                blank=True,
                help_text="Adresse d’expéditeur pour l’e-mail (sinon paramètre par défaut du serveur).",
            ),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='smtp_host',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='smtp_password',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='smtp_port',
            field=models.PositiveIntegerField(default=587),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='smtp_use_ssl',
            field=models.BooleanField(
                default=False,
                help_text='Implicit TLS (e.g. port 465). Leave off if using STARTTLS (587).',
            ),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='smtp_use_tls',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='smtp_user',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.RunPython(ensure_single_org_settings, noop_reverse),
    ]
