# Generated by Django 6.0.4 on 2026-04-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_users_view_permission_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pref_currency',
            field=models.CharField(choices=[('EUR', 'Euro (€)'), ('XOF', 'Franc CFA (BCEAO)'), ('USD', 'Dollar (US)'), ('CNY', 'Yuan renminbi (¥)')], default='EUR', max_length=8),
        ),
    ]
