# Generated by Django 6.0.4 on 2026-04-30 10:50

from django.db import migrations


def seed_categories(apps, schema_editor):
    Category = apps.get_model("api", "Category")
    names = [
        "Ciment & Liants",
        "Fer à béton & Acier",
        "Bois & Coffrage",
        "Agrégats & Base",
        "Quincaillerie & Consommables",
        "EPI",
        "Outillage",
        "Équipements & Petits matériels",
        "Matériels loués",
        "Pièces de rechange",
    ]
    for name in names:
        Category.objects.get_or_create(name=name, parent=None)


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_supplier_item_inventory_v2"),
    ]

    operations = [
        migrations.RunPython(seed_categories, migrations.RunPython.noop),
    ]
