# Generated by Django 5.2.13 on 2026-05-05 10:18

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_seed_units_of_measure'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_stock_movements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='movements/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='loss_reason',
            field=models.CharField(blank=True, choices=[('perte', 'Perte'), ('casse', 'Casse / Détérioration'), ('vol', 'Vol'), ('peremption', 'Péremption'), ('autre', 'Autre')], max_length=32),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='reference_number',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('pending', 'En attente de validation'), ('approved', 'Validé'), ('rejected', 'Rejeté'), ('completed', 'Exécuté')], default='draft', max_length=32),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='unit_price_at_movement',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('entree', 'Entrée (Réception Fournisseur)'), ('sortie', 'Sortie (Usage Chantier)'), ('transfert', 'Transfert Inter-Sites'), ('retour', 'Retour de Chantier'), ('ajustement', 'Ajustement / Correction')], max_length=16),
        ),
        migrations.CreateModel(
            name='ApprovalRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('movement_type', models.CharField(choices=[('entree', 'Entrée (Réception Fournisseur)'), ('sortie', 'Sortie (Usage Chantier)'), ('transfert', 'Transfert Inter-Sites'), ('retour', 'Retour de Chantier'), ('ajustement', 'Ajustement / Correction')], max_length=16)),
                ('min_value_threshold', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('is_active', models.BooleanField(default=True)),
                ('approver_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_rules', to='api.role')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_rules', to='api.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['movement_type', 'min_value_threshold'],
            },
        ),
    ]
