# Generated by Django 5.2.13 on 2026-05-28 11:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_storagelocation_v2'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectresource',
            options={'ordering': ['project', 'resource_kind', 'name']},
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='default_currency',
            field=models.CharField(default='XOF', max_length=8),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='stock_valuation_method',
            field=models.CharField(choices=[('last_price', "Dernier prix d'achat connu"), ('wac', 'Coût moyen pondéré (CUMP)'), ('fifo', 'FIFO / PEPS (Premier entré, premier sorti)')], default='wac', help_text='Méthode de valorisation des sorties de stock vers les chantiers.', max_length=16),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='vat_rate_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Taux de TVA par défaut appliqué aux coûts (0 = désactivé).', max_digits=5),
        ),
        migrations.AddField(
            model_name='projectresource',
            name='cost_unit',
            field=models.CharField(blank=True, choices=[('jour', 'par Jour'), ('heure', 'par Heure'), ('forfait', 'Forfait')], max_length=16),
        ),
        migrations.AddField(
            model_name='projectresource',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectresource',
            name='planned_duration',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Durée planifiée (jours ou heures selon cost_unit).', null=True),
        ),
        migrations.AddField(
            model_name='projectresource',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='FCFA/jour (matériel), FCFA/h (MO), FCFA forfait (sous-traitance).', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='projectresource',
            name='resource_kind',
            field=models.CharField(choices=[('equipment', 'Matériel'), ('subcontract', 'Sous-traitance'), ('main_oeuvre', "Main d'œuvre")], default='equipment', max_length=32),
        ),
        migrations.CreateModel(
            name='StockCostLayer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=14)),
                ('quantity_in', models.DecimalField(decimal_places=3, max_digits=14)),
                ('quantity_remaining', models.DecimalField(decimal_places=3, max_digits=14)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_layers', to='api.item')),
                ('source_movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opened_cost_layers', to='api.stockmovement')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['item', 'occurred_at'],
                'indexes': [models.Index(fields=['item', 'occurred_at'], name='api_stockco_item_id_a5939b_idx')],
            },
        ),
    ]
