# Generated by Django 5.2.13 on 2026-06-03 15:40

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_seed_initial_cost_layers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsettings',
            name='abnormal_movement_threshold',
            field=models.DecimalField(decimal_places=2, default=Decimal('500000'), help_text="Valeur minimale (FCFA) d'une sortie pour declencher une alerte mouvement eleve.", max_digits=14),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='email_alerts_enabled',
            field=models.BooleanField(default=True, help_text='Envoyer un email pour les alertes de severite critique.'),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='inventory_gap_min_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('50000'), help_text="Seuil minimal (FCFA) d'un ajustement perte pour declencher une alerte.", max_digits=14),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='inventory_gap_min_qty_percent',
            field=models.PositiveSmallIntegerField(default=10, help_text="Seuil minimal (% du stock) d'un ajustement perte pour declencher une alerte."),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='new_delivery_alerts_enabled',
            field=models.BooleanField(default=True, help_text='Generer une alerte (info) a chaque nouvelle livraison receptionnee.'),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='notification_email',
            field=models.EmailField(blank=True, help_text="Email destinataire des alertes critiques (vide = email de l'org).", max_length=254),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='pending_approval_threshold_hours',
            field=models.PositiveSmallIntegerField(default=24, help_text="Duree (heures) avant alerte pour un mouvement en attente d'approbation."),
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('alert_type', models.CharField(choices=[('low_stock', 'Stock bas'), ('stockout', 'Rupture de stock'), ('budget_overrun', 'Depassement de budget'), ('new_delivery', 'Nouvelle livraison'), ('pending_approval', 'Validation en attente'), ('inventory_gap', "Ecart d'inventaire"), ('abnormal_movement', 'Mouvement eleve')], max_length=32)),
                ('severity', models.CharField(choices=[('critical', 'Critique'), ('warning', 'Avertissement'), ('info', 'Information')], max_length=16)),
                ('status', models.CharField(choices=[('unread', 'Non lue'), ('read', 'Lue'), ('dismissed', 'Ignoree'), ('resolved', 'Resolue automatiquement')], default='unread', max_length=16)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('fingerprint', models.CharField(db_index=True, max_length=128)),
                ('email_sent', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='api.item')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='api.project')),
                ('stock_movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='api.stockmovement')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='api_alert_status_fea25f_idx'), models.Index(fields=['alert_type', 'status'], name='api_alert_alert_t_18414f_idx'), models.Index(fields=['fingerprint', 'status'], name='api_alert_fingerp_28e82f_idx')],
            },
        ),
    ]
